name: Update README with Current Time

on:
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update timestamp in README.md
        run: |
          TIMESTAMP=$(date +"%s")
          # Thay thế placeholder <!--TIME--> bằng timestamp hiện tại
          sed -i "s|<!--TIME-->|$TIMESTAMP|g" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -am "Update README with current timestamp" || echo "No changes to commit"
          git push
